import type { Category, Product } from "./types";

export const categories: Category[] = [
  {
    id: "10000000-0000-0000-0000-000000000001",
    slug: "trockenbau-platten",
    name: "Trockenbau & Platten",
    shortName: "Trockenbau",
    description: "Gipskarton, Profile und Bauplatten für flexible Innenausbauten.",
    number: "01",
    filterKeys: ["Stärke", "Format", "Eigenschaft"],
  },
  {
    id: "10000000-0000-0000-0000-000000000002",
    slug: "zement-bauchemie",
    name: "Zement, Mörtel & Bauchemie",
    shortName: "Zement & Bauchemie",
    description: "Zement, Mörtel, Estrich und Kleber für belastbare Ergebnisse.",
    number: "02",
    filterKeys: ["Gebinde", "Anwendung", "Festigkeit"],
  },
  {
    id: "10000000-0000-0000-0000-000000000003",
    slug: "daemmung-folien",
    name: "Dämmung & Folien",
    shortName: "Dämmung & Folien",
    description: "Wärme-, Schall- und Feuchteschutz für Dach, Wand und Boden.",
    number: "03",
    filterKeys: ["Stärke", "Material", "WLG"],
  },
  {
    id: "10000000-0000-0000-0000-000000000004",
    slug: "holz-bauplatten",
    name: "Holz & Bauplatten",
    shortName: "Holz & Bauplatten",
    description: "OSB, Sperrholz, MDF und Konstruktionsholz in verlässlicher Qualität.",
    number: "04",
    filterKeys: ["Stärke", "Format", "Holzart"],
  },
  {
    id: "10000000-0000-0000-0000-000000000005",
    slug: "mauerwerk-steine",
    name: "Mauerwerk & Steine",
    shortName: "Mauerwerk & Steine",
    description: "Ziegel, Porenbeton und Pflaster für Rohbau und Außenanlagen.",
    number: "05",
    filterKeys: ["Format", "Material", "Druckfestigkeit"],
  },
  {
    id: "10000000-0000-0000-0000-000000000006",
    slug: "dach-entwaesserung",
    name: "Dach & Entwässerung",
    shortName: "Dach & Entwässerung",
    description: "Dachbahnen, Rinnen und Zubehör für dauerhaft trockene Gebäude.",
    number: "06",
    filterKeys: ["Material", "Länge", "Farbe"],
  },
];

const images = {
  drywall:
    "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=82",
  cement:
    "https://images.unsplash.com/photo-1542621334-a254cf47733d?auto=format&fit=crop&w=1200&q=82",
  insulation:
    "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=82",
  wood: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6?auto=format&fit=crop&w=1200&q=82",
  bricks:
    "https://images.unsplash.com/photo-1625337902947-dc6f0eef6a4f?auto=format&fit=crop&w=1200&q=82",
  roof: "https://images.unsplash.com/photo-1632759145351-1d592919f522?auto=format&fit=crop&w=1200&q=82",
};

type ProductSeed = Omit<Product, "id" | "inventory" | "imageAlt"> & { stock?: [number, number] };

const seeds: ProductSeed[] = [
  {
    slug: "gipskartonplatte-pro-125",
    categorySlug: "trockenbau-platten",
    sku: "NW-125-260",
    brand: "Nordwand",
    name: "Gipskartonplatte Pro 12,5 mm",
    shortDescription: "Universelle Ausbauplatte für Wand und Decke.",
    description:
      "Formstabile Gipskartonplatte für Metall- und Holzunterkonstruktionen im trockenen Innenbereich. Saubere Kanten erleichtern die schnelle Montage und Verspachtelung.",
    price: 8.95,
    saleUnit: "Stück",
    basePrice: 5.74,
    baseUnit: "m²",
    baseQuantity: 1.56,
    coveragePerUnit: 1.56,
    weightKg: 13.2,
    image: images.drywall,
    featured: true,
    aliases: ["Rigips", "Gipsplatte", "GK Platte"],
    specs: { Stärke: "12,5 mm", Format: "600 × 2600 mm", Eigenschaft: "Standard" },
    variantGroup: "gipskarton",
    variantLabel: "Standard",
    stock: [86, 240],
  },
  {
    slug: "gipskartonplatte-feuchtraum-125",
    categorySlug: "trockenbau-platten",
    sku: "NW-F125-260",
    brand: "Nordwand",
    name: "Gipskartonplatte Feuchtraum 12,5 mm",
    shortDescription: "Imprägnierte Platte für Bad und Küche.",
    description:
      "Feuchtebeständige Ausbauplatte mit reduzierter Wasseraufnahme für häusliche Feuchträume. Geeignet für Wand- und Deckenbekleidungen.",
    price: 13.49,
    saleUnit: "Stück",
    basePrice: 8.65,
    baseUnit: "m²",
    baseQuantity: 1.56,
    coveragePerUnit: 1.56,
    weightKg: 13.8,
    image: images.drywall,
    featured: true,
    aliases: ["grüne Rigipsplatte", "GKBI", "Feuchtraumplatte"],
    specs: { Stärke: "12,5 mm", Format: "600 × 2600 mm", Eigenschaft: "Feuchtraum" },
    variantGroup: "gipskarton",
    variantLabel: "Feuchtraum",
    stock: [44, 128],
  },
  {
    slug: "brandschutzplatte-df-15",
    categorySlug: "trockenbau-platten",
    sku: "NW-DF15-200",
    brand: "Nordwand",
    name: "Brandschutzplatte DF 15 mm",
    shortDescription: "Faserverstärkte Platte für erhöhten Brandschutz.",
    description:
      "Nicht brennbare Spezialplatte mit dichtem Gipskern für brandschutztechnisch anspruchsvolle Innenausbauten.",
    price: 17.9,
    saleUnit: "Stück",
    basePrice: 14.92,
    baseUnit: "m²",
    baseQuantity: 1.2,
    coveragePerUnit: 1.2,
    weightKg: 15.5,
    image: images.drywall,
    featured: false,
    aliases: ["Feuerschutzplatte", "GKF", "Brandschutz Rigips"],
    specs: { Stärke: "15 mm", Format: "600 × 2000 mm", Eigenschaft: "Brandschutz" },
    variantGroup: "gipskarton",
    variantLabel: "Brandschutz",
    stock: [19, 64],
  },
  {
    slug: "cw-profil-75",
    categorySlug: "trockenbau-platten",
    sku: "PRO-CW75-260",
    brand: "Profilux",
    name: "CW-Ständerprofil 75 mm",
    shortDescription: "Verzinktes Metallprofil für Trennwände.",
    description:
      "Stabiles CW-Profil mit geprägter Oberfläche für die schnelle Montage nichttragender Trockenbauwände.",
    price: 6.49,
    saleUnit: "Stück",
    basePrice: 2.5,
    baseUnit: "m",
    baseQuantity: 2.6,
    weightKg: 1.65,
    image: images.drywall,
    featured: false,
    aliases: ["Metallständer", "Trockenbauprofil", "CW Profil"],
    specs: { Stärke: "0,6 mm", Format: "75 × 2600 mm", Eigenschaft: "Verzinkt" },
    stock: [125, 460],
  },

  {
    slug: "universal-zement-cem2-25",
    categorySlug: "zement-bauchemie",
    sku: "MV-CEM25",
    brand: "Massivon",
    name: "Universal Zement CEM II 25 kg",
    shortDescription: "Vielseitiger Portlandkompositzement.",
    description:
      "Für Beton, Estrich und Mauermörtel im Innen- und Außenbereich. Gleichmäßige Verarbeitung und verlässliche Frühfestigkeit.",
    price: 9.79,
    saleUnit: "Sack",
    basePrice: 0.39,
    baseUnit: "kg",
    baseQuantity: 25,
    weightKg: 25,
    image: images.cement,
    featured: true,
    aliases: ["Portlandzement", "Zement 25kg", "Beton Zement"],
    specs: { Gebinde: "25 kg", Anwendung: "Innen & außen", Festigkeit: "32,5 R" },
    stock: [72, 310],
  },
  {
    slug: "schnellmoertel-10",
    categorySlug: "zement-bauchemie",
    sku: "MV-SM10",
    brand: "Massivon",
    name: "Schnellmörtel Fix 10 kg",
    shortDescription: "Schnell abbindender Montagemörtel.",
    description:
      "Für zügige Ausbesserungen, Befestigungen und Montagen. Bereits nach kurzer Zeit belastbar und frostbeständig.",
    price: 14.9,
    saleUnit: "Sack",
    basePrice: 1.49,
    baseUnit: "kg",
    baseQuantity: 10,
    weightKg: 10,
    image: images.cement,
    featured: false,
    aliases: ["Blitzzement", "Reparaturmörtel", "Montagemörtel"],
    specs: { Gebinde: "10 kg", Anwendung: "Montage", Festigkeit: "Schnell" },
    stock: [31, 94],
  },
  {
    slug: "nivelliermasse-20",
    categorySlug: "zement-bauchemie",
    sku: "PLAN-N20",
    brand: "Planum",
    name: "Nivelliermasse Flow 20 kg",
    shortDescription: "Selbstverlaufend von 2 bis 20 mm.",
    description:
      "Emissionsarme Bodenausgleichsmasse für gleichmäßige Untergründe unter Fliesen und Bodenbelägen.",
    price: 25.5,
    saleUnit: "Sack",
    basePrice: 1.28,
    baseUnit: "kg",
    baseQuantity: 20,
    coveragePerUnit: 4.0,
    weightKg: 20,
    image: images.cement,
    featured: true,
    aliases: ["Ausgleichsmasse", "Fließspachtel", "Bodenausgleich"],
    specs: { Gebinde: "20 kg", Anwendung: "Boden", Festigkeit: "CT-C25" },
    stock: [27, 108],
  },
  {
    slug: "flexkleber-c2te-25",
    categorySlug: "zement-bauchemie",
    sku: "PLAN-FK25",
    brand: "Planum",
    name: "Flexkleber C2 TE 25 kg",
    shortDescription: "Standfester Kleber für Fliese und Feinsteinzeug.",
    description:
      "Flexibler Dünnbettmörtel mit verlängerter offener Zeit für innen und außen, auch auf Fußbodenheizung.",
    price: 19.95,
    saleUnit: "Sack",
    basePrice: 0.8,
    baseUnit: "kg",
    baseQuantity: 25,
    coveragePerUnit: 7.5,
    weightKg: 25,
    image: images.cement,
    featured: false,
    aliases: ["Fliesenkleber", "Feinsteinzeugkleber", "Kleber C2"],
    specs: { Gebinde: "25 kg", Anwendung: "Fliese", Festigkeit: "C2 TE" },
    stock: [51, 180],
  },

  {
    slug: "mineralwolle-035-100",
    categorySlug: "daemmung-folien",
    sku: "THERM-035-100",
    brand: "Thermara",
    name: "Mineralwolle WLG 035 100 mm",
    shortDescription: "Nicht brennbare Klemmfilz-Dämmung.",
    description:
      "Elastischer Dämmstoff für Zwischensparren, Vorsatzschalen und leichte Trennwände mit guter Wärme- und Schalldämmung.",
    price: 42.9,
    saleUnit: "Paket",
    basePrice: 8.58,
    baseUnit: "m²",
    baseQuantity: 5,
    coveragePerUnit: 5,
    weightKg: 12.5,
    image: images.insulation,
    featured: true,
    aliases: ["Mineralwolle", "Glaswolle", "Isolierung"],
    specs: { Stärke: "100 mm", Material: "Mineralwolle", WLG: "035" },
    variantGroup: "mineralwolle",
    variantLabel: "100 mm",
    stock: [23, 78],
  },
  {
    slug: "mineralwolle-035-160",
    categorySlug: "daemmung-folien",
    sku: "THERM-035-160",
    brand: "Thermara",
    name: "Mineralwolle WLG 035 160 mm",
    shortDescription: "Starke Dämmlage für Dach und Fassade.",
    description:
      "Komprimierter Klemmfilz mit hoher Rückstellkraft für anspruchsvolle Wärmedämmungen und effektiven Schallschutz.",
    price: 54.9,
    saleUnit: "Paket",
    basePrice: 13.73,
    baseUnit: "m²",
    baseQuantity: 4,
    coveragePerUnit: 4,
    weightKg: 15.8,
    image: images.insulation,
    featured: false,
    aliases: ["Mineralwolle", "Glaswolle", "Dachdämmung"],
    specs: { Stärke: "160 mm", Material: "Mineralwolle", WLG: "035" },
    variantGroup: "mineralwolle",
    variantLabel: "160 mm",
    stock: [12, 46],
  },
  {
    slug: "xps-daemmplatte-50",
    categorySlug: "daemmung-folien",
    sku: "THERM-XPS50",
    brand: "Thermara",
    name: "XPS-Dämmplatte 50 mm",
    shortDescription: "Druckfeste Dämmung für Sockel und Boden.",
    description:
      "Feuchteunempfindliche Hartschaumplatte mit Stufenfalz für erdberührte Bauteile und hoch belastete Flächen.",
    price: 38.4,
    saleUnit: "Paket",
    basePrice: 12.8,
    baseUnit: "m²",
    baseQuantity: 3,
    coveragePerUnit: 3,
    weightKg: 8.9,
    image: images.insulation,
    featured: false,
    aliases: ["Styrodur", "Perimeterdämmung", "Hartschaum"],
    specs: { Stärke: "50 mm", Material: "XPS", WLG: "035" },
    stock: [18, 61],
  },
  {
    slug: "dampfbremse-pro-50",
    categorySlug: "daemmung-folien",
    sku: "KLIMA-DB50",
    brand: "Klimaflex",
    name: "Dampfbremse Pro 50 m²",
    shortDescription: "Variable Klimamembran für den Innenausbau.",
    description:
      "Reißfeste Dampfbremsfolie für luftdichte Konstruktionen an Dach und Wand. Rasterdruck erleichtert Zuschnitt und Montage.",
    price: 79.9,
    saleUnit: "Rolle",
    basePrice: 1.6,
    baseUnit: "m²",
    baseQuantity: 50,
    coveragePerUnit: 50,
    weightKg: 8.2,
    image: images.insulation,
    featured: true,
    aliases: ["Dampfsperre", "Klimamembran", "Folie Dach"],
    specs: { Stärke: "0,2 mm", Material: "Polyolefin", WLG: "–" },
    stock: [14, 52],
  },

  {
    slug: "osb3-verlegeplatte-18",
    categorySlug: "holz-bauplatten",
    sku: "HF-OSB18",
    brand: "Holzform",
    name: "OSB 3 Verlegeplatte 18 mm",
    shortDescription: "Tragfähige Platte mit Nut und Feder.",
    description:
      "Feuchtebeständige OSB/3-Platte für Böden, Wände und Dachausbau. Passgenaue Nut-und-Feder-Kanten für schnelle Verlegung.",
    price: 24.9,
    saleUnit: "Stück",
    basePrice: 7.97,
    baseUnit: "m²",
    baseQuantity: 3.125,
    coveragePerUnit: 3.125,
    weightKg: 36.2,
    image: images.wood,
    featured: true,
    aliases: ["Grobspanplatte", "OSB Platte", "Verlegeplatte"],
    specs: { Stärke: "18 mm", Format: "1250 × 2500 mm", Holzart: "Nadelholz" },
    variantGroup: "osb",
    variantLabel: "18 mm",
    stock: [38, 142],
  },
  {
    slug: "osb3-verlegeplatte-22",
    categorySlug: "holz-bauplatten",
    sku: "HF-OSB22",
    brand: "Holzform",
    name: "OSB 3 Verlegeplatte 22 mm",
    shortDescription: "Extra starke Platte für belastete Flächen.",
    description:
      "Robuste OSB/3-Platte mit Nut und Feder für höher belastete Fußboden- und Dachkonstruktionen.",
    price: 31.5,
    saleUnit: "Stück",
    basePrice: 10.08,
    baseUnit: "m²",
    baseQuantity: 3.125,
    coveragePerUnit: 3.125,
    weightKg: 43.8,
    image: images.wood,
    featured: false,
    aliases: ["Grobspanplatte", "OSB Boden", "Verlegeplatte"],
    specs: { Stärke: "22 mm", Format: "1250 × 2500 mm", Holzart: "Nadelholz" },
    variantGroup: "osb",
    variantLabel: "22 mm",
    stock: [21, 95],
  },
  {
    slug: "multiplexplatte-birke-15",
    categorySlug: "holz-bauplatten",
    sku: "HF-MPX15",
    brand: "Holzform",
    name: "Multiplexplatte Birke 15 mm",
    shortDescription: "Formstabile Qualitätsplatte für Möbel und Ausbau.",
    description:
      "Mehrlagig verleimte Birkenplatte mit fein geschliffener Oberfläche und attraktiver Kante.",
    price: 59.9,
    saleUnit: "Stück",
    basePrice: 31.95,
    baseUnit: "m²",
    baseQuantity: 1.875,
    coveragePerUnit: 1.875,
    weightKg: 19.6,
    image: images.wood,
    featured: true,
    aliases: ["Sperrholz", "Birkenmultiplex", "Holzplatte"],
    specs: { Stärke: "15 mm", Format: "1250 × 1500 mm", Holzart: "Birke" },
    stock: [15, 48],
  },
  {
    slug: "kvh-fichte-60x80",
    categorySlug: "holz-bauplatten",
    sku: "HF-KVH6080",
    brand: "Holzform",
    name: "Konstruktionsvollholz Fichte 60 × 80 mm",
    shortDescription: "Gehobeltes KVH für tragende Konstruktionen.",
    description:
      "Technisch getrocknetes, maßhaltiges Vollholz mit gefasten Kanten für Carport, Dach und Holzrahmenbau.",
    price: 21.6,
    saleUnit: "Stück",
    basePrice: 4.5,
    baseUnit: "m",
    baseQuantity: 4.8,
    weightKg: 10.5,
    image: images.wood,
    featured: false,
    aliases: ["KVH", "Kantholz", "Balken"],
    specs: { Stärke: "60 × 80 mm", Format: "4800 mm", Holzart: "Fichte" },
    stock: [34, 120],
  },

  {
    slug: "hochlochziegel-thermo-24",
    categorySlug: "mauerwerk-steine",
    sku: "SW-HLZ24",
    brand: "Steinwerk",
    name: "Hochlochziegel Thermo 24",
    shortDescription: "Wärmedämmender Ziegel für Außenwände.",
    description:
      "Plangeschliffener Hochlochziegel für wirtschaftliches Mauerwerk mit guten Wärmedämmeigenschaften.",
    price: 3.49,
    saleUnit: "Stück",
    basePrice: 43.63,
    baseUnit: "m²",
    baseQuantity: 0.08,
    weightKg: 13.4,
    image: images.bricks,
    featured: true,
    aliases: ["Poroton", "Mauerziegel", "Lochziegel"],
    specs: { Format: "373 × 240 × 249 mm", Material: "Ton", Druckfestigkeit: "Klasse 10" },
    stock: [214, 980],
  },
  {
    slug: "kalksandstein-12df",
    categorySlug: "mauerwerk-steine",
    sku: "SW-KS12",
    brand: "Steinwerk",
    name: "Kalksandstein 12 DF",
    shortDescription: "Massiver Planstein mit hohem Schallschutz.",
    description:
      "Maßhaltiger Kalksandstein für tragende und nichttragende Wände mit hoher Rohdichte.",
    price: 4.29,
    saleUnit: "Stück",
    basePrice: 53.63,
    baseUnit: "m²",
    baseQuantity: 0.08,
    weightKg: 18.7,
    image: images.bricks,
    featured: false,
    aliases: ["KS Stein", "Planstein", "Kalksand"],
    specs: {
      Format: "248 × 240 × 238 mm",
      Material: "Kalksandstein",
      Druckfestigkeit: "Klasse 12",
    },
    stock: [168, 740],
  },
  {
    slug: "porenbeton-planblock-175",
    categorySlug: "mauerwerk-steine",
    sku: "SW-PB175",
    brand: "Steinwerk",
    name: "Porenbeton Planblock 17,5 cm",
    shortDescription: "Leichter Planblock für schnelles Mauerwerk.",
    description:
      "Leicht zu bearbeitender Porenbetonstein mit exakter Maßhaltigkeit für Innen- und Außenwände.",
    price: 5.79,
    saleUnit: "Stück",
    basePrice: 48.25,
    baseUnit: "m²",
    baseQuantity: 0.12,
    weightKg: 12.8,
    image: images.bricks,
    featured: true,
    aliases: ["Ytong", "Gasbeton", "Porenbetonstein"],
    specs: { Format: "599 × 175 × 199 mm", Material: "Porenbeton", Druckfestigkeit: "PP2" },
    stock: [96, 410],
  },
  {
    slug: "betonpflaster-grau-20x10",
    categorySlug: "mauerwerk-steine",
    sku: "SW-PFL2010",
    brand: "Steinwerk",
    name: "Betonpflaster Grau 20 × 10 cm",
    shortDescription: "Klassischer Pflasterstein für Wege und Einfahrten.",
    description:
      "Robuster Betonstein mit gefaster Kante und gleichmäßiger Oberfläche für belastbare Außenflächen.",
    price: 0.59,
    saleUnit: "Stück",
    basePrice: 29.5,
    baseUnit: "m²",
    baseQuantity: 0.02,
    weightKg: 2.7,
    image: images.bricks,
    featured: false,
    aliases: ["Pflasterstein", "Betonstein", "Gehwegstein"],
    specs: { Format: "200 × 100 × 80 mm", Material: "Beton", Druckfestigkeit: "DIN EN 1338" },
    stock: [540, 2200],
  },

  {
    slug: "bitumen-schweissbahn-v60",
    categorySlug: "dach-entwaesserung",
    sku: "DACH-V60",
    brand: "Dachstrom",
    name: "Bitumen-Schweißbahn V60 S4",
    shortDescription: "Sichere Abdichtung für Dach und Bauwerk.",
    description:
      "Besandete Elastomerbitumenbahn mit Glasvlieseinlage für mehrlagige Dachabdichtungen.",
    price: 39.9,
    saleUnit: "Rolle",
    basePrice: 5.7,
    baseUnit: "m²",
    baseQuantity: 7,
    coveragePerUnit: 7,
    weightKg: 31,
    image: images.roof,
    featured: true,
    aliases: ["Dachpappe", "Bitumenbahn", "Schweißbahn"],
    specs: { Material: "Bitumen", Länge: "7,5 m", Farbe: "Schwarz" },
    stock: [28, 112],
  },
  {
    slug: "unterdeckbahn-150",
    categorySlug: "dach-entwaesserung",
    sku: "DACH-U150",
    brand: "Dachstrom",
    name: "Unterdeckbahn Protect 150",
    shortDescription: "Diffusionsoffene Bahn für Steildächer.",
    description:
      "Reißfeste dreilagige Unterdeckbahn mit hohem Sd-Wert für winddichte und regensichere Dachkonstruktionen.",
    price: 89.0,
    saleUnit: "Rolle",
    basePrice: 1.19,
    baseUnit: "m²",
    baseQuantity: 75,
    coveragePerUnit: 75,
    weightKg: 11.2,
    image: images.roof,
    featured: false,
    aliases: ["Unterspannbahn", "Dachfolie", "Dachmembran"],
    specs: { Material: "Polypropylen", Länge: "50 m", Farbe: "Anthrazit" },
    stock: [16, 59],
  },
  {
    slug: "dachrinne-zink-125-2m",
    categorySlug: "dach-entwaesserung",
    sku: "RAIN-Z125-2",
    brand: "Rainform",
    name: "Dachrinne Zink NW 125, 2 m",
    shortDescription: "Langlebige Halbrundrinne aus Titanzink.",
    description:
      "Formstabile Rinne mit sauberem Wulst für Einfamilienhaus, Garage und Nebengebäude.",
    price: 22.9,
    saleUnit: "Stück",
    basePrice: 11.45,
    baseUnit: "m",
    baseQuantity: 2,
    weightKg: 2.9,
    image: images.roof,
    featured: true,
    aliases: ["Regenrinne", "Zinkrinne", "Dachentwässerung"],
    specs: { Material: "Titanzink", Länge: "2 m", Farbe: "Natur" },
    variantGroup: "rinne",
    variantLabel: "Zink",
    stock: [42, 154],
  },
  {
    slug: "fallrohr-anthrazit-dn90-2m",
    categorySlug: "dach-entwaesserung",
    sku: "RAIN-A90-2",
    brand: "Rainform",
    name: "Fallrohr Anthrazit DN 90, 2 m",
    shortDescription: "Beschichtetes Fallrohr für moderne Fassaden.",
    description:
      "Witterungsbeständiges Stahl-Fallrohr mit farbstabiler Beschichtung und passgenauen Steckmuffen.",
    price: 28.5,
    saleUnit: "Stück",
    basePrice: 14.25,
    baseUnit: "m",
    baseQuantity: 2,
    weightKg: 3.4,
    image: images.roof,
    featured: false,
    aliases: ["Regenrohr", "Dachrohr", "Ablaufrohr"],
    specs: { Material: "Beschichteter Stahl", Länge: "2 m", Farbe: "Anthrazit" },
    stock: [26, 88],
  },
];

export const products: Product[] = seeds.map((seed, index) => {
  const { stock = [20, 80], ...product } = seed;
  return {
    ...product,
    id: `20000000-0000-0000-0000-${String(index + 1).padStart(12, "0")}`,
    imageAlt: `${product.name} – Produktabbildung`,
    inventory: {
      berlin: stock[0],
      warehouse: stock[1],
      pickup: stock[0] > 0,
      delivery: stock[1] > 0,
      leadTime: stock[0] > 0 ? "Abholbereit in 2 Stunden" : "Lieferbar in 2–4 Werktagen",
    },
  };
});
