import { images, type ProductSeed } from "./shared";

export const coreProductSeeds: ProductSeed[] = [
  {
    slug: "gipskartonplatte-pro-125",
    categorySlug: "trockenbau-platten",
    sku: "00002886",
    brand: "Knauf",
    name: "Bauplatte GKB 12,5 mm",
    shortDescription: "Universelle Ausbauplatte für Wand und Decke.",
    description:
      "Formstabile Gipskartonplatte für Metall- und Holzunterkonstruktionen im trockenen Innenbereich. Saubere Kanten erleichtern die schnelle Montage und Verspachtelung.",
    price: 8.95,
    saleUnit: "Stück",
    basePrice: 5.74,
    baseUnit: "m²",
    baseQuantity: 1.56,
    coveragePerUnit: 1.56,
    weightKg: 13.2,
    image: images.drywall,
    featured: true,
    aliases: ["Rigips", "Gipsplatte", "GK Platte"],
    specs: { Stärke: "12,5 mm", Format: "600 × 2600 mm", Eigenschaft: "Standard" },
    variantGroup: "gipskarton",
    variantLabel: "Standard",
    stock: [86, 240],
  },
  {
    slug: "gipskartonplatte-feuchtraum-125",
    categorySlug: "trockenbau-platten",
    sku: "00579400",
    brand: "Knauf",
    name: "Diamant GKFI 12,5 mm",
    shortDescription: "Imprägnierte Platte für Bad und Küche.",
    description:
      "Feuchtebeständige Ausbauplatte mit reduzierter Wasseraufnahme für häusliche Feuchträume. Geeignet für Wand- und Deckenbekleidungen.",
    price: 13.49,
    saleUnit: "Stück",
    basePrice: 8.65,
    baseUnit: "m²",
    baseQuantity: 1.56,
    coveragePerUnit: 1.56,
    weightKg: 13.8,
    image: images.drywall,
    featured: true,
    aliases: ["grüne Rigipsplatte", "GKBI", "Feuchtraumplatte"],
    specs: { Stärke: "12,5 mm", Format: "600 × 2600 mm", Eigenschaft: "Feuchtraum" },
    variantGroup: "gipskarton",
    variantLabel: "Feuchtraum",
    stock: [44, 128],
  },
  {
    slug: "brandschutzplatte-df-15",
    categorySlug: "trockenbau-platten",
    sku: "GKF-15-2000",
    brand: "Knauf",
    name: "Feuerschutzplatte GKF 15 mm",
    shortDescription: "Faserverstärkte Platte für erhöhten Brandschutz.",
    description:
      "Nicht brennbare Spezialplatte mit dichtem Gipskern für brandschutztechnisch anspruchsvolle Innenausbauten.",
    price: 17.9,
    saleUnit: "Stück",
    basePrice: 14.92,
    baseUnit: "m²",
    baseQuantity: 1.2,
    coveragePerUnit: 1.2,
    weightKg: 15.5,
    image: images.drywall,
    featured: false,
    aliases: ["Feuerschutzplatte", "GKF", "Brandschutz Rigips"],
    specs: { Stärke: "15 mm", Format: "600 × 2000 mm", Eigenschaft: "Brandschutz" },
    variantGroup: "gipskarton",
    variantLabel: "Brandschutz",
    stock: [19, 64],
  },
  {
    slug: "cw-profil-75",
    categorySlug: "trockenbau-platten",
    sku: "CW-75-50-06-2600",
    brand: "Knauf",
    name: "CW-Ständerprofil 75 mm",
    shortDescription: "Verzinktes Metallprofil für Trennwände.",
    description:
      "Stabiles CW-Profil mit geprägter Oberfläche für die schnelle Montage nichttragender Trockenbauwände.",
    price: 6.49,
    saleUnit: "Stück",
    basePrice: 2.5,
    baseUnit: "m",
    baseQuantity: 2.6,
    weightKg: 1.65,
    image: images.drywall,
    featured: false,
    aliases: ["Metallständer", "Trockenbauprofil", "CW Profil"],
    specs: { Stärke: "0,6 mm", Format: "75 × 2600 mm", Eigenschaft: "Verzinkt" },
    stock: [125, 460],
  },

  {
    slug: "universal-zement-cem2-25",
    categorySlug: "zement-bauchemie",
    sku: "SAKRET-PZ-25",
    brand: "SAKRET",
    name: "Portlandzement CEM I 42,5 R 25 kg",
    shortDescription: "Vielseitiger Portlandkompositzement.",
    description:
      "Für Beton, Estrich und Mauermörtel im Innen- und Außenbereich. Gleichmäßige Verarbeitung und verlässliche Frühfestigkeit.",
    price: 9.79,
    saleUnit: "Sack",
    basePrice: 0.39,
    baseUnit: "kg",
    baseQuantity: 25,
    weightKg: 25,
    image: images.cement,
    featured: true,
    aliases: ["Portlandzement", "Zement 25kg", "Beton Zement"],
    specs: { Gebinde: "25 kg", Anwendung: "Innen & außen", Festigkeit: "32,5 R" },
    stock: [72, 310],
  },
  {
    slug: "schnellmoertel-10",
    categorySlug: "zement-bauchemie",
    sku: "QM-RZB-25",
    brand: "quick-mix",
    name: "Ruck-Zuck Beton 25 kg",
    shortDescription: "Schnell abbindender Montagemörtel.",
    description:
      "Für zügige Ausbesserungen, Befestigungen und Montagen. Bereits nach kurzer Zeit belastbar und frostbeständig.",
    price: 14.9,
    saleUnit: "Sack",
    basePrice: 1.49,
    baseUnit: "kg",
    baseQuantity: 10,
    weightKg: 10,
    image: images.cement,
    featured: false,
    aliases: ["Blitzzement", "Reparaturmörtel", "Montagemörtel"],
    specs: { Gebinde: "10 kg", Anwendung: "Montage", Festigkeit: "Schnell" },
    stock: [31, 94],
  },
  {
    slug: "nivelliermasse-20",
    categorySlug: "zement-bauchemie",
    sku: "ARDEX-K22F-20",
    brand: "ARDEX",
    name: "K 22 F Ausgleichsmasse 20 kg",
    shortDescription: "Selbstverlaufend von 2 bis 20 mm.",
    description:
      "Emissionsarme Bodenausgleichsmasse für gleichmäßige Untergründe unter Fliesen und Bodenbelägen.",
    price: 25.5,
    saleUnit: "Sack",
    basePrice: 1.28,
    baseUnit: "kg",
    baseQuantity: 20,
    coveragePerUnit: 4.0,
    weightKg: 20,
    image: images.cement,
    featured: true,
    aliases: ["Ausgleichsmasse", "Fließspachtel", "Bodenausgleich"],
    specs: { Gebinde: "20 kg", Anwendung: "Boden", Festigkeit: "CT-C25" },
    stock: [27, 108],
  },
  {
    slug: "flexkleber-c2te-25",
    categorySlug: "zement-bauchemie",
    sku: "SAKRET-FK-25",
    brand: "SAKRET",
    name: "Flexkleber C2 TE 25 kg",
    shortDescription: "Standfester Kleber für Fliese und Feinsteinzeug.",
    description:
      "Flexibler Dünnbettmörtel mit verlängerter offener Zeit für innen und außen, auch auf Fußbodenheizung.",
    price: 19.95,
    saleUnit: "Sack",
    basePrice: 0.8,
    baseUnit: "kg",
    baseQuantity: 25,
    coveragePerUnit: 7.5,
    weightKg: 25,
    image: images.cement,
    featured: false,
    aliases: ["Fliesenkleber", "Feinsteinzeugkleber", "Kleber C2"],
    specs: { Gebinde: "25 kg", Anwendung: "Fliese", Festigkeit: "C2 TE" },
    stock: [51, 180],
  },

  {
    slug: "mineralwolle-035-100",
    categorySlug: "daemmung-folien",
    sku: "UNIFIT-035-100",
    brand: "Knauf Insulation",
    name: "UNIFIT 035 Klemmfilz 100 mm",
    shortDescription: "Nicht brennbare Klemmfilz-Dämmung.",
    description:
      "Elastischer Dämmstoff für Zwischensparren, Vorsatzschalen und leichte Trennwände mit guter Wärme- und Schalldämmung.",
    price: 42.9,
    saleUnit: "Paket",
    basePrice: 8.58,
    baseUnit: "m²",
    baseQuantity: 5,
    coveragePerUnit: 5,
    weightKg: 12.5,
    image: images.insulation,
    featured: true,
    aliases: ["Mineralwolle", "Glaswolle", "Isolierung"],
    specs: { Stärke: "100 mm", Material: "Mineralwolle", WLG: "035" },
    variantGroup: "mineralwolle",
    variantLabel: "100 mm",
    stock: [23, 78],
  },
  {
    slug: "mineralwolle-035-160",
    categorySlug: "daemmung-folien",
    sku: "UNIFIT-035-160",
    brand: "Knauf Insulation",
    name: "UNIFIT 035 Klemmfilz 160 mm",
    shortDescription: "Starke Dämmlage für Dach und Fassade.",
    description:
      "Komprimierter Klemmfilz mit hoher Rückstellkraft für anspruchsvolle Wärmedämmungen und effektiven Schallschutz.",
    price: 54.9,
    saleUnit: "Paket",
    basePrice: 13.73,
    baseUnit: "m²",
    baseQuantity: 4,
    coveragePerUnit: 4,
    weightKg: 15.8,
    image: images.insulation,
    featured: false,
    aliases: ["Mineralwolle", "Glaswolle", "Dachdämmung"],
    specs: { Stärke: "160 mm", Material: "Mineralwolle", WLG: "035" },
    variantGroup: "mineralwolle",
    variantLabel: "160 mm",
    stock: [12, 46],
  },
  {
    slug: "xps-daemmplatte-50",
    categorySlug: "daemmung-folien",
    sku: "JACKODUR-ATLAS-300-50",
    brand: "JACKON",
    name: "JACKODUR Atlas 300 50 mm",
    shortDescription: "Druckfeste Dämmung für Sockel und Boden.",
    description:
      "Feuchteunempfindliche Hartschaumplatte mit Stufenfalz für erdberührte Bauteile und hoch belastete Flächen.",
    price: 38.4,
    saleUnit: "Paket",
    basePrice: 12.8,
    baseUnit: "m²",
    baseQuantity: 3,
    coveragePerUnit: 3,
    weightKg: 8.9,
    image: images.insulation,
    featured: false,
    aliases: ["Styrodur", "Perimeterdämmung", "Hartschaum"],
    specs: { Stärke: "50 mm", Material: "XPS", WLG: "035" },
    stock: [18, 61],
  },
  {
    slug: "dampfbremse-pro-50",
    categorySlug: "daemmung-folien",
    sku: "INTELLO-PLUS-75",
    brand: "pro clima",
    name: "INTELLO PLUS Dampfbremse 75 m²",
    shortDescription: "Variable Klimamembran für den Innenausbau.",
    description:
      "Reißfeste Dampfbremsfolie für luftdichte Konstruktionen an Dach und Wand. Rasterdruck erleichtert Zuschnitt und Montage.",
    price: 79.9,
    saleUnit: "Rolle",
    basePrice: 1.6,
    baseUnit: "m²",
    baseQuantity: 50,
    coveragePerUnit: 50,
    weightKg: 8.2,
    image: images.insulation,
    featured: true,
    aliases: ["Dampfsperre", "Klimamembran", "Folie Dach"],
    specs: { Stärke: "0,2 mm", Material: "Polyolefin", WLG: "–" },
    stock: [14, 52],
  },

];
