import { images, type ProductSeed } from "./shared";

export const structureProductSeeds: ProductSeed[] = [
  {
    slug: "osb3-verlegeplatte-18",
    categorySlug: "holz-bauplatten",
    sku: "EGGER-OSB3-18",
    brand: "EGGER",
    name: "OSB 3 Verlegeplatte 18 mm",
    shortDescription: "Tragfähige Platte mit Nut und Feder.",
    description:
      "Feuchtebeständige OSB/3-Platte für Böden, Wände und Dachausbau. Passgenaue Nut-und-Feder-Kanten für schnelle Verlegung.",
    price: 24.9,
    saleUnit: "Stück",
    basePrice: 7.97,
    baseUnit: "m²",
    baseQuantity: 3.125,
    coveragePerUnit: 3.125,
    weightKg: 36.2,
    image: images.wood,
    featured: true,
    aliases: ["Grobspanplatte", "OSB Platte", "Verlegeplatte"],
    specs: { Stärke: "18 mm", Format: "1250 × 2500 mm", Holzart: "Nadelholz" },
    variantGroup: "osb",
    variantLabel: "18 mm",
    stock: [38, 142],
  },
  {
    slug: "osb3-verlegeplatte-22",
    categorySlug: "holz-bauplatten",
    sku: "EGGER-OSB3-22",
    brand: "EGGER",
    name: "OSB 3 Verlegeplatte 22 mm",
    shortDescription: "Extra starke Platte für belastete Flächen.",
    description:
      "Robuste OSB/3-Platte mit Nut und Feder für höher belastete Fußboden- und Dachkonstruktionen.",
    price: 31.5,
    saleUnit: "Stück",
    basePrice: 10.08,
    baseUnit: "m²",
    baseQuantity: 3.125,
    coveragePerUnit: 3.125,
    weightKg: 43.8,
    image: images.wood,
    featured: false,
    aliases: ["Grobspanplatte", "OSB Boden", "Verlegeplatte"],
    specs: { Stärke: "22 mm", Format: "1250 × 2500 mm", Holzart: "Nadelholz" },
    variantGroup: "osb",
    variantLabel: "22 mm",
    stock: [21, 95],
  },
  {
    slug: "multiplexplatte-birke-15",
    categorySlug: "holz-bauplatten",
    sku: "METSA-BIRCH-15",
    brand: "Metsä Wood",
    name: "Birch Multiplex 15 mm",
    shortDescription: "Formstabile Qualitätsplatte für Möbel und Ausbau.",
    description:
      "Mehrlagig verleimte Birkenplatte mit fein geschliffener Oberfläche und attraktiver Kante.",
    price: 59.9,
    saleUnit: "Stück",
    basePrice: 31.95,
    baseUnit: "m²",
    baseQuantity: 1.875,
    coveragePerUnit: 1.875,
    weightKg: 19.6,
    image: images.wood,
    featured: true,
    aliases: ["Sperrholz", "Birkenmultiplex", "Holzplatte"],
    specs: { Stärke: "15 mm", Format: "1250 × 1500 mm", Holzart: "Birke" },
    stock: [15, 48],
  },
  {
    slug: "kvh-fichte-60x80",
    categorySlug: "holz-bauplatten",
    sku: "DERIX-KVH-6080-4800",
    brand: "DERIX",
    name: "Konstruktionsvollholz Fichte 60 × 80 mm",
    shortDescription: "Gehobeltes KVH für tragende Konstruktionen.",
    description:
      "Technisch getrocknetes, maßhaltiges Vollholz mit gefasten Kanten für Carport, Dach und Holzrahmenbau.",
    price: 21.6,
    saleUnit: "Stück",
    basePrice: 4.5,
    baseUnit: "m",
    baseQuantity: 4.8,
    weightKg: 10.5,
    image: images.wood,
    featured: false,
    aliases: ["KVH", "Kantholz", "Balken"],
    specs: { Stärke: "60 × 80 mm", Format: "4800 mm", Holzart: "Fichte" },
    stock: [34, 120],
  },

  {
    slug: "hochlochziegel-thermo-24",
    categorySlug: "mauerwerk-steine",
    sku: "POROTON-T8-24",
    brand: "Wienerberger",
    name: "Poroton-T8 24,0 cm",
    shortDescription: "Wärmedämmender Ziegel für Außenwände.",
    description:
      "Plangeschliffener Hochlochziegel für wirtschaftliches Mauerwerk mit guten Wärmedämmeigenschaften.",
    price: 3.49,
    saleUnit: "Stück",
    basePrice: 43.63,
    baseUnit: "m²",
    baseQuantity: 0.08,
    weightKg: 13.4,
    image: images.bricks,
    featured: true,
    aliases: ["Poroton", "Mauerziegel", "Lochziegel"],
    specs: { Format: "373 × 240 × 249 mm", Material: "Ton", Druckfestigkeit: "Klasse 10" },
    stock: [214, 980],
  },
  {
    slug: "kalksandstein-12df",
    categorySlug: "mauerwerk-steine",
    sku: "KS-ORIGINAL-12DF",
    brand: "KS-ORIGINAL",
    name: "KS-Planstein 12 DF",
    shortDescription: "Massiver Planstein mit hohem Schallschutz.",
    description:
      "Maßhaltiger Kalksandstein für tragende und nichttragende Wände mit hoher Rohdichte.",
    price: 4.29,
    saleUnit: "Stück",
    basePrice: 53.63,
    baseUnit: "m²",
    baseQuantity: 0.08,
    weightKg: 18.7,
    image: images.bricks,
    featured: false,
    aliases: ["KS Stein", "Planstein", "Kalksand"],
    specs: {
      Format: "248 × 240 × 238 mm",
      Material: "Kalksandstein",
      Druckfestigkeit: "Klasse 12",
    },
    stock: [168, 740],
  },
  {
    slug: "porenbeton-planblock-175",
    categorySlug: "mauerwerk-steine",
    sku: "YTONG-P2-17.5",
    brand: "Ytong",
    name: "Ytong Planblock 17,5 cm",
    shortDescription: "Leichter Planblock für schnelles Mauerwerk.",
    description:
      "Leicht zu bearbeitender Porenbetonstein mit exakter Maßhaltigkeit für Innen- und Außenwände.",
    price: 5.79,
    saleUnit: "Stück",
    basePrice: 48.25,
    baseUnit: "m²",
    baseQuantity: 0.12,
    weightKg: 12.8,
    image: images.bricks,
    featured: true,
    aliases: ["Ytong", "Gasbeton", "Porenbetonstein"],
    specs: { Format: "599 × 175 × 199 mm", Material: "Porenbeton", Druckfestigkeit: "PP2" },
    stock: [96, 410],
  },
  {
    slug: "betonpflaster-grau-20x10",
    categorySlug: "mauerwerk-steine",
    sku: "EHL-RECHTECK-20X10X8",
    brand: "EHL",
    name: "Rechteckpflaster 20 × 10 × 8 cm Grau",
    shortDescription: "Klassischer Pflasterstein für Wege und Einfahrten.",
    description:
      "Robuster Betonstein mit gefaster Kante und gleichmäßiger Oberfläche für belastbare Außenflächen.",
    price: 0.59,
    saleUnit: "Stück",
    basePrice: 29.5,
    baseUnit: "m²",
    baseQuantity: 0.02,
    weightKg: 2.7,
    image: images.bricks,
    featured: false,
    aliases: ["Pflasterstein", "Betonstein", "Gehwegstein"],
    specs: { Format: "200 × 100 × 80 mm", Material: "Beton", Druckfestigkeit: "DIN EN 1338" },
    stock: [540, 2200],
  },

  {
    slug: "bitumen-schweissbahn-v60",
    categorySlug: "dach-entwaesserung",
    sku: "BAUDER-PYE-PV200-S5",
    brand: "Bauder",
    name: "BauderPYE PV200 S5",
    shortDescription: "Sichere Abdichtung für Dach und Bauwerk.",
    description:
      "Besandete Elastomerbitumenbahn mit Glasvlieseinlage für mehrlagige Dachabdichtungen.",
    price: 39.9,
    saleUnit: "Rolle",
    basePrice: 5.7,
    baseUnit: "m²",
    baseQuantity: 7,
    coveragePerUnit: 7,
    weightKg: 31,
    image: images.roof,
    featured: true,
    aliases: ["Dachpappe", "Bitumenbahn", "Schweißbahn"],
    specs: { Material: "Bitumen", Länge: "7,5 m", Farbe: "Schwarz" },
    stock: [28, 112],
  },
  {
    slug: "unterdeckbahn-150",
    categorySlug: "dach-entwaesserung",
    sku: "DELTA-VENT-N",
    brand: "Dörken",
    name: "DELTA-VENT N Unterdeckbahn",
    shortDescription: "Diffusionsoffene Bahn für Steildächer.",
    description:
      "Reißfeste dreilagige Unterdeckbahn mit hohem Sd-Wert für winddichte und regensichere Dachkonstruktionen.",
    price: 89.0,
    saleUnit: "Rolle",
    basePrice: 1.19,
    baseUnit: "m²",
    baseQuantity: 75,
    coveragePerUnit: 75,
    weightKg: 11.2,
    image: images.roof,
    featured: false,
    aliases: ["Unterspannbahn", "Dachfolie", "Dachmembran"],
    specs: { Material: "Polypropylen", Länge: "50 m", Farbe: "Anthrazit" },
    stock: [16, 59],
  },
  {
    slug: "dachrinne-zink-125-2m",
    categorySlug: "dach-entwaesserung",
    sku: "RHEINZINK-RHEINZINK-125-2M",
    brand: "RHEINZINK",
    name: "Dachrinne halbrund 125, 2 m",
    shortDescription: "Langlebige Halbrundrinne aus Titanzink.",
    description:
      "Formstabile Rinne mit sauberem Wulst für Einfamilienhaus, Garage und Nebengebäude.",
    price: 22.9,
    saleUnit: "Stück",
    basePrice: 11.45,
    baseUnit: "m",
    baseQuantity: 2,
    weightKg: 2.9,
    image: images.roof,
    featured: true,
    aliases: ["Regenrinne", "Zinkrinne", "Dachentwässerung"],
    specs: { Material: "Titanzink", Länge: "2 m", Farbe: "Natur" },
    variantGroup: "rinne",
    variantLabel: "Zink",
    stock: [42, 154],
  },
  {
    slug: "fallrohr-anthrazit-dn90-2m",
    categorySlug: "dach-entwaesserung",
    sku: "MARLEY-DN87-2M-ANTHRAZIT",
    brand: "Marley",
    name: "Fallrohr DN 87, 2 m Anthrazit",
    shortDescription: "Beschichtetes Fallrohr für moderne Fassaden.",
    description:
      "Witterungsbeständiges Stahl-Fallrohr mit farbstabiler Beschichtung und passgenauen Steckmuffen.",
    price: 28.5,
    saleUnit: "Stück",
    basePrice: 14.25,
    baseUnit: "m",
    baseQuantity: 2,
    weightKg: 3.4,
    image: images.roof,
    featured: false,
    aliases: ["Regenrohr", "Dachrohr", "Ablaufrohr"],
    specs: { Material: "Beschichteter Stahl", Länge: "2 m", Farbe: "Anthrazit" },
    stock: [26, 88],
  },
];
